version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      # Port d'accès web de Jenkins (http://localhost:8080)
      - "8080:8080"
        # Port dʼagent Jenkins (connexion à distance des agents)
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
