name: CI/CD ELK Stack

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Vérification du docker-compose
        run: docker-compose -f elk/docker-compose.yml config

      - name: Construction des services
        run: docker-compose -f elk/docker-compose.yml build
